#!/usr/bin/env python3
"""Dev-time generator for `fylke_geo.py` — the committed, simplified geographic
geometry of Norway's 15 fylker (2024) as inline SVG paths.

RFC-001 P5 forbids external map tiles/CDN at serve time, so we fetch open
boundary data ONCE here (Kartverket-derived, via the robhop/fylker-og-kommuner
GeoJSON), project it to Web Mercator (the shape everyone recognises Norway
from), simplify it aggressively (Douglas–Peucker + tiny-island drop), and bake
the result into a committed Python module. Production never runs this — it just
serves the committed paths. Re-run only to refresh the boundaries:

    cd web && python3 make_fylke_geo.py && python3 build.py

Source: https://github.com/robhop/fylker-og-kommuner (Kartverket, CC BY 4.0).
"""
import json
import math
import os
import urllib.request

SOURCE_URL = ("https://raw.githubusercontent.com/robhop/fylker-og-kommuner/"
              "main/Fylker-M.geojson")
SOURCE_CREDIT = "Kartverket via robhop/fylker-og-kommuner (CC BY 4.0)"

# Aggressive simplification — this is a schematic choropleth, not a survey map.
# Tolerances are in FINAL PIXEL units (after projection + scale to WIDTH).
WIDTH = 360.0             # target SVG width; height follows Norway's aspect
TOLERANCE = 0.7           # Douglas–Peucker tolerance, px
MIN_RING_AREA = 5.0       # drop islands/rings smaller than this, px²
DECIMALS = 1


def _mercator(lon, lat):
    x = math.radians(lon)
    y = math.log(math.tan(math.pi / 4 + math.radians(lat) / 2))
    return x, y


def _perp_dist(p, a, b):
    (px, py), (ax, ay), (bx, by) = p, a, b
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def _rdp(pts, tol):
    if len(pts) < 3:
        return pts
    dmax, idx = 0.0, 0
    for i in range(1, len(pts) - 1):
        d = _perp_dist(pts[i], pts[0], pts[-1])
        if d > dmax:
            dmax, idx = d, i
    if dmax > tol:
        left = _rdp(pts[:idx + 1], tol)
        right = _rdp(pts[idx:], tol)
        return left[:-1] + right
    return [pts[0], pts[-1]]


def _ring_area(ring):
    a = 0.0
    for i in range(len(ring) - 1):
        x0, y0 = ring[i]
        x1, y1 = ring[i + 1]
        a += x0 * y1 - x1 * y0
    return abs(a) / 2.0


def _rings(geom):
    """Yield each exterior ring (list of [lon,lat]) of a (Multi)Polygon."""
    t = geom["type"]
    polys = geom["coordinates"] if t == "MultiPolygon" else [geom["coordinates"]]
    for poly in polys:
        yield poly[0]  # exterior ring only — holes are invisible at this scale


def build():
    raw = json.loads(urllib.request.urlopen(SOURCE_URL, timeout=60).read())

    # Project every ring to Mercator, tracking global bounds, so we can scale
    # the whole country to WIDTH before simplifying in pixel units.
    projected = {}
    minx = miny = 1e18
    maxx = maxy = -1e18
    for f in raw["features"]:
        name = f["properties"]["name"]
        rings = []
        for ring in _rings(f["geometry"]):
            pr = [_mercator(lon, lat) for lon, lat in ring]
            rings.append(pr)
            for x, y in pr:
                minx, miny = min(minx, x), min(miny, y)
                maxx, maxy = max(maxx, x), max(maxy, y)
        projected[name] = rings

    scale = WIDTH / (maxx - minx)
    height = (maxy - miny) * scale

    def to_px(x, y):
        return ((x - minx) * scale, (maxy - y) * scale)  # flip: SVG y grows down

    paths = {}
    for name, rings in projected.items():
        d = []
        for ring in rings:
            px = [to_px(x, y) for x, y in ring]
            if _ring_area(px) < MIN_RING_AREA:
                continue  # island/sliver too small to see — drop it
            px = _rdp(px, TOLERANCE)
            if len(px) < 4:
                continue
            d.append("M" + " ".join(
                "{},{}".format(round(x, DECIMALS), round(y, DECIMALS))
                for x, y in px) + "Z")
        paths[name] = "".join(d)

    viewbox = "0 0 {} {}".format(round(WIDTH, DECIMALS), round(height, DECIMALS))
    total = sum(len(p) for p in paths.values())

    out = os.path.join(os.path.dirname(__file__), "fylke_geo.py")
    with open(out, "w") as fh:
        fh.write('"""Simplified geographic geometry of Norway\'s 15 fylker (2024) as\n')
        fh.write("inline SVG paths — GENERATED by make_fylke_geo.py, committed so\n")
        fh.write("production serves it with no external map tile (RFC-001 P5).\n")
        fh.write('Source: ' + SOURCE_CREDIT + '.\n"""\n')
        fh.write("FYLKE_VIEWBOX = {!r}\n\n".format(viewbox))
        fh.write("FYLKE_SOURCE = {!r}\n\n".format(SOURCE_CREDIT))
        fh.write("FYLKE_PATHS = {\n")
        for name in sorted(paths):
            fh.write("    {!r}: {!r},\n".format(name, paths[name]))
        fh.write("}\n")
    print("wrote {} ({} fylker, {} path chars, viewBox {})".format(
        out, len(paths), total, viewbox))


if __name__ == "__main__":
    build()
